USE [master]
GO
/****** Object:  Database [COMPANY_DB]    Script Date: 5/21/2024 12:41:29 AM ******/
CREATE DATABASE [COMPANY_DB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'COMPANY_DB', FILENAME = N'D:\PROGRAM\SQLSERVER\MSSQL16.MSSQLSERVER\MSSQL16.MSSQLSERVER\MSSQL\DATA\COMPANY_DB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'COMPANY_DB_log', FILENAME = N'D:\PROGRAM\SQLSERVER\MSSQL16.MSSQLSERVER\MSSQL16.MSSQLSERVER\MSSQL\DATA\COMPANY_DB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [COMPANY_DB] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [COMPANY_DB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [COMPANY_DB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [COMPANY_DB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [COMPANY_DB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [COMPANY_DB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [COMPANY_DB] SET ARITHABORT OFF 
GO
ALTER DATABASE [COMPANY_DB] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [COMPANY_DB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [COMPANY_DB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [COMPANY_DB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [COMPANY_DB] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [COMPANY_DB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [COMPANY_DB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [COMPANY_DB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [COMPANY_DB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [COMPANY_DB] SET  ENABLE_BROKER 
GO
ALTER DATABASE [COMPANY_DB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [COMPANY_DB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [COMPANY_DB] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [COMPANY_DB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [COMPANY_DB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [COMPANY_DB] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [COMPANY_DB] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [COMPANY_DB] SET RECOVERY FULL 
GO
ALTER DATABASE [COMPANY_DB] SET  MULTI_USER 
GO
ALTER DATABASE [COMPANY_DB] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [COMPANY_DB] SET DB_CHAINING OFF 
GO
ALTER DATABASE [COMPANY_DB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [COMPANY_DB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [COMPANY_DB] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [COMPANY_DB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'COMPANY_DB', N'ON'
GO
ALTER DATABASE [COMPANY_DB] SET QUERY_STORE = ON
GO
ALTER DATABASE [COMPANY_DB] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [COMPANY_DB]
GO
/****** Object:  Table [dbo].[CATEGORY]    Script Date: 5/21/2024 12:41:30 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CATEGORY](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[NAME] [nvarchar](1000) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[COMPANY]    Script Date: 5/21/2024 12:41:30 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[COMPANY](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[NAME] [nvarchar](1000) NULL,
	[LOCATED] [text] NULL,
	[FACEBOOK] [nvarchar](1000) NULL,
	[X] [nvarchar](1000) NULL,
	[EMAIL] [varchar](100) NULL,
	[PHONE] [varchar](20) NULL,
	[FOCUSEDfIELD] [nvarchar](1000) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[DEPARTMENT]    Script Date: 5/21/2024 12:41:30 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DEPARTMENT](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[COMPANY_ID] [int] NULL,
	[DESCRIPTION] [text] NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[EMPLOYEE]    Script Date: 5/21/2024 12:41:30 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[EMPLOYEE](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[DEPARTMENT_ID] [int] NULL,
	[USER_ACCOUNT_ID] [int] NULL,
	[FULLNAME] [nvarchar](1000) NULL,
	[DATE_OF_BIRTH] [date] NULL,
	[ID_NO] [varchar](12) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[USER_ACCOUNT_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[POST]    Script Date: 5/21/2024 12:41:30 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[POST](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[CATEGORY_ID] [int] NULL,
	[USER_ACCOUNT_ID] [int] NULL,
	[TITLE] [nvarchar](1000) NULL,
	[THUMBNAIL] [varbinary](max) NULL,
	[CONTENT] [varchar](12) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ROLE]    Script Date: 5/21/2024 12:41:30 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ROLE](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[NAME] [varchar](100) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SCHEDULES]    Script Date: 5/21/2024 12:41:30 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SCHEDULES](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[EMPLOYEE_ID] [int] NULL,
	[TASK_ID] [int] NULL,
	[DETAILS_TASK] [nvarchar](1000) NULL,
	[STATUS] [nvarchar](200) NULL,
	[ID_NO] [varchar](12) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TASK]    Script Date: 5/21/2024 12:41:30 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TASK](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[NAME] [text] NULL,
	[TASK_DESCRIPTION] [text] NULL,
	[EXPECTED_END_DATE] [date] NULL,
	[START_DATE] [date] NULL,
	[TEAM_SIZE] [int] NULL,
	[STATUS] [nvarchar](30) NULL,
	[THUMBAIL] [varbinary](max) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[USER_ACCOUNT]    Script Date: 5/21/2024 12:41:30 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[USER_ACCOUNT](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[ROLE_ID] [int] NULL,
	[USERNAME] [nvarchar](1000) NULL,
	[PASSWORD] [text] NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[DEPARTMENT]  WITH CHECK ADD FOREIGN KEY([COMPANY_ID])
REFERENCES [dbo].[COMPANY] ([ID])
GO
ALTER TABLE [dbo].[EMPLOYEE]  WITH CHECK ADD FOREIGN KEY([DEPARTMENT_ID])
REFERENCES [dbo].[DEPARTMENT] ([ID])
GO
ALTER TABLE [dbo].[EMPLOYEE]  WITH CHECK ADD FOREIGN KEY([USER_ACCOUNT_ID])
REFERENCES [dbo].[USER_ACCOUNT] ([ID])
GO
ALTER TABLE [dbo].[POST]  WITH CHECK ADD FOREIGN KEY([CATEGORY_ID])
REFERENCES [dbo].[CATEGORY] ([ID])
GO
ALTER TABLE [dbo].[POST]  WITH CHECK ADD FOREIGN KEY([USER_ACCOUNT_ID])
REFERENCES [dbo].[USER_ACCOUNT] ([ID])
GO
ALTER TABLE [dbo].[SCHEDULES]  WITH CHECK ADD FOREIGN KEY([EMPLOYEE_ID])
REFERENCES [dbo].[EMPLOYEE] ([ID])
GO
ALTER TABLE [dbo].[SCHEDULES]  WITH CHECK ADD FOREIGN KEY([TASK_ID])
REFERENCES [dbo].[TASK] ([ID])
GO
ALTER TABLE [dbo].[USER_ACCOUNT]  WITH CHECK ADD FOREIGN KEY([ROLE_ID])
REFERENCES [dbo].[ROLE] ([ID])
GO
USE [master]
GO
ALTER DATABASE [COMPANY_DB] SET  READ_WRITE 
GO
